// client-old/src/templates/atoms/Source.svelte
<!-- Source.svelte -->
<script>
    // console.log('Hello Basis from Header.svelte');
</script>

<div class="source">
    <div class="content">
        <img src="./assets/media/figma-logo.svg" alt="logo">
        <p class="txt_caption">Ariane Design System</p>
    </div>
</div>

<style lang="scss">
    @import './../utils';

    .source {
        padding: 4px;
        border-radius: 4px;
        border: 1px solid $bgGrey;
        display: inline-block;

        .content {
            display: flex;
            align-items: center;
        }

        p {
            font-family: $bold;
            margin-left: 8px;
        }
    }
</style>

// client/components/Atoms/Source/Source.vue
<template>
  <div class="source">
    <div class="content">
      <img src="~assets/img/figma-logo.svg" alt="logo">
      <p class="txt_caption">
        Ariane Design System
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Source'
}
</script>

<style scoped lang="scss">
@import "Source";
</style>
