// client/src/templates/layout/Table.svelte
<!-- Table.svelte -->
<script>
    // console.log('Hello Basis from Header.svelte');
    import Dropdown from '../fields/Dropdown.svelte';
    import Search from '../fields/Search.svelte';
    import LineTableColor from '../components/LineTableColor.svelte';
</script>

<div class=table>
    <div class="table-search">
        <Search />
        <Dropdown />
    </div>

    <div class="table-title">
        <div class="grow1 input">
            <input type="checkbox" id="scales" name="scales">
        </div>
        <div class="grow2">
            <p class="txt_caption">Token name</p>
        </div>
        <div class="grow1">
            <p class="txt_caption">Preview</p>
        </div>
        <div class="grow1">
            <p class="txt_caption">Value</p>
        </div>
        <div class="grow2">
            <p class="txt_caption">Last update</p>
        </div>
        <div class="grow1">
            <p class="txt_caption">Status</p>
        </div>
        <div class="grow2">
            <p class="txt_caption">Source</p>
        </div>
    </div>

    <LineTableColor />
    <LineTableColor />
    <LineTableColor />
</div>

<style lang="scss">
    @import './../utils';

    .table {
        background: $white;
        border-radius: 8px;
        box-shadow: $shadowheader;

        &-search {
            padding: 16px;
            display: flex;
            justify-content: space-between;
        }

        &-title {
            display: flex;
            align-items: center;
            padding: 8px 16px;
            border-top: 1px solid $greyLight;
            background: $bgGrey;

            div {
                flex: 1 1;

                p {
                    color: $grey;
                    text-transform: uppercase;
                    font-family: $bold;
                    color: $grey2;
                }

                &.grow1 {
                    flex-grow: 1;
                }
                &.grow2 {
                    flex-grow: 2;
                }
                &.input {
                    max-width: 30px;
                }
            }
        }
    }
</style>

// client/components/Table/Table.vue
<template>
  <div class="table">
    <div class="table-search">
      <Search />
      <Dropdown />
    </div>

    <div class="table-title">
      <div class="grow1 input">
        <input type="checkbox">
      </div>
      <div class="grow2">
        <p class="txt_caption">Token name</p>
      </div>
      <div class="grow1">
        <p class="txt_caption">Preview</p>
      </div>
      <div class="grow1">
        <p class="txt_caption">Value</p>
      </div>
      <div class="grow2">
        <p class="txt_caption">Last update</p>
      </div>
      <div class="grow1">
        <p class="txt_caption">Status</p>
      </div>
      <div class="grow2">
        <p class="txt_caption">Source</p>
      </div>
    </div>

    <div>
      <TableColorRow />
      <TableColorRow />
      <TableColorRow />
    </div>

    <BarCheckboxSelect />
  </div>
</template>

<script>
import Search from '~/components/Fields/Search/Search'
import Dropdown from '~/components/Fields/Dropdown/Dropdown'
import TableColorRow from '~/components/TableColorRow/TableColorRow'
import BarCheckboxSelect from '~/components/BarCheckboxSelect/BarCheckboxSelect'

export default {
  name: 'Table',
  components: {
    Search,
    Dropdown,
    TableColorRow,
    BarCheckboxSelect
  }
}
</script>

<style scoped lang="scss">
@import "Table";
</style>
