// client/components/Atoms/Status/Status.vue
<template>
  <div>
    <div class="is-green tag">
      <p class="txt_caption">
        Published
      </p>
    </div>

    <!-- <div class="is-orange tag">
        <p class='txt_caption'>Updated</p>
    </div> -->
  </div>
</template>

<script>
export default {
  name: 'Status'
}
</script>

<style scoped lang="scss">
@import "Status";
</style>

// client/src/templates/atoms/Status.svelte
<!-- Status.svelte -->
<script>
    // console.log('Hello Basis from Header.svelte');
</script>

<div>
    <div class="is-green tag">
        <p class='txt_caption'>Published</p>
    </div>

    <!-- <div class="is-orange tag">
        <p class='txt_caption'>Updated</p>
    </div> -->
</div>

<style lang="scss">
    @import './../utils';

    .tag {
        padding: 4px;
        border-radius: 4px;
        display: inline-block;

        p {
            font-family: $bold;
        }
    }

    .is-green {
        background: $bgGreen;

        p {
            color: $green;
        }
    }

    .is-orange {
        background: $bgOrange;

        p {
            color: $orange;
        }
    }
</style>
